"use client";
import {useMemo,useState} from "react";
import {createClient} from "../lib/supabase/client";
import AdminStoreCrmCard from "./AdminStoreCrmCard";
import AdminQrPanel from "./AdminQrPanel";
import BrandContentImporter from "./BrandContentImporter";
import styles from "./AdminV2.module.css";

const themes:any={livraison:"🚲 Nouveau vélo, nouveau départ !",nouveaute:"✨ Nouveauté au magasin !",arrivage:"📦 Nouvel arrivage !",atelier:"🔧 Du côté de l’atelier",promo:"🏷️ Offre du moment !",magasin:"🏪 La vie du magasin",vendeur:"👋 L’équipe du magasin",conseil:"💡 Le conseil du magasin",evenement:"🏁 Rendez-vous au magasin !"};
const themeLabels:any={livraison:"Livraison d’un vélo",nouveaute:"Nouveauté",arrivage:"Arrivage",atelier:"Atelier",promo:"Promotion",magasin:"Vie du magasin",vendeur:"Équipe",conseil:"Conseil",evenement:"Événement"};
const caption=(type:string,store:any)=>{const name=store?.name||"notre magasin",city=store?.city?" à "+store.city:"";return (themes[type]||themes.magasin)+"\n\n"+(type==="livraison"?"Une nouvelle livraison vient d’arriver chez ":type==="atelier"?"Notre équipe prend soin de vos vélos chez ":type==="promo"?"Une offre à découvrir chez ":"Retrouve toute l’actualité de ")+name+city+".\n\n#Velo #"+String(name).replace(/[^a-z0-9]/gi,"")};
const slug=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export default function AdminV2(p:any){
 const {stores,brands,sources,products,qrBatches,platformSettings,socialPosts,socialPhotos=[],brandSocial=[],brandVariants=[],accessStatus=[],socialMonitors=[],brandStoreCounts=[],storeBrands=[]}=p;
 const s=createClient();
 const [tab,setTab]=useState("overview"),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[openBrand,setOpenBrand]=useState<string|null>(null),[newStore,setNewStore]=useState(false),[brandName,setBrandName]=useState(""),[brandId,setBrandId]=useState(brands.find((b:any)=>b.name==="Orbea")?.id||brands[0]?.id||""),[year,setYear]=useState("2027"),[dataBrand,setDataBrand]=useState("all"),[dataYear,setDataYear]=useState("all"),[sourceType,setSourceType]=useState("ftp"),[sourceUrl,setSourceUrl]=useState(""),[communityFilter,setCommunityFilter]=useState<"all"|"brand"|"store">("all"),[communityBrand,setCommunityBrand]=useState("all"),[communityStore,setCommunityStore]=useState("all"),[photoTheme,setPhotoTheme]=useState<Record<string,string>>({}),[siteDraft,setSiteDraft]=useState<any>(platformSettings.site_editor_draft||{}),[sections,setSections]=useState<Record<string,boolean>>({validate:true,photos:true,created:true}),[brandInvite,setBrandInvite]=useState<Record<string,string>>({}),[checkingBrand,setCheckingBrand]=useState<string|null>(null);
 const pending=brandSocial.filter((x:any)=>x.status==="pending"), availableBrands=brandSocial.filter((x:any)=>x.status==="available"), availablePhotos=socialPhotos.filter((x:any)=>x.status==="available");
 const storeCount=(id:string)=>Number(brandStoreCounts.find((x:any)=>x.brand_id===id)?.store_count||0);
 const brandCount=(id:string)=>storeBrands.filter((x:any)=>x.store_id===id).length;
 const configuredPlv=qrBatches.reduce((n:number,b:any)=>n+Number(b.store_id?b.quantity:0),0);
 const sourceYears=Array.from(new Set(sources.map((x:any)=>String(x.model_year||"")).filter(Boolean))).sort().reverse();
 const filteredSources=sources.filter((x:any)=>(dataBrand==="all"||x.brand_id===dataBrand)&&(dataYear==="all"||String(x.model_year)===dataYear));
 const created=[...availableBrands.map((x:any)=>({...x,_kind:"brand"})),...socialPosts.filter((x:any)=>x.source_type==="store").map((x:any)=>({...x,_kind:"store"}))].filter((x:any)=>(communityFilter==="all"||x._kind===communityFilter)&&(communityBrand==="all"||x.brand_id===communityBrand)&&(communityStore==="all"||x.store_id===communityStore));
 const nav=[["overview","Vue d’ensemble"],["stores","Magasins"],["brands","Marques"],["data","EPOS & flux"],["qr","Lots PLV"],["community","Community Management"],["site","Site par défaut"]];
 const goto=(x:string)=>setTab(x);
 async function uploadPlatform(kind:"rectangle"|"square",f:File){setBusy(true);const path="platform/logo-"+kind+"-"+Date.now()+"."+((f.name.split(".").pop())||"png");const up=await s.storage.from("brand-assets").upload(path,f,{contentType:f.type,upsert:true});if(!up.error){const url=s.storage.from("brand-assets").getPublicUrl(path).data.publicUrl;await s.from("platform_settings").update({[kind==="rectangle"?"logo_rectangle_url":"logo_square_url"]:url}).eq("id",1);location.reload()}else alert(up.error.message);setBusy(false)}
 async function addBrand(){if(!brandName.trim())return;setBusy(true);const {error}=await s.from("brands").insert({name:brandName.trim(),slug:slug(brandName)});setBusy(false);if(error)alert(error.message);else location.reload()}
 async function brandLogo(b:any,f:File){setBusy(true);const path="logos/"+b.slug+"-"+Date.now()+"."+((f.name.split(".").pop())||"png");const up=await s.storage.from("brand-assets").upload(path,f,{contentType:f.type});if(!up.error){const url=s.storage.from("brand-assets").getPublicUrl(path).data.publicUrl;await s.from("brands").update({logo_url:url}).eq("id",b.id);location.reload()}else alert(up.error.message);setBusy(false)}
 async function inviteBrand(b:any){const r=await fetch("/api/admin/brand-invite",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({brandId:b.id})});const x=await r.json();if(!r.ok)return alert(x.error||"Invitation impossible");const l=location.origin+"/marque/connexion?activation="+encodeURIComponent(x.token);setBrandInvite(v=>({...v,[b.id]:l}));navigator.clipboard.writeText(l)}
 async function saveMonitor(b:any,url:string,enabled:boolean){setBusy(true);const {error}=await s.rpc("admin_upsert_brand_social_monitor",{p_brand_id:b.id,p_facebook_page_url:url,p_enabled:enabled});setBusy(false);if(error)alert(error.message);else location.reload()}
 async function checkMonitor(b:any){setBusy(true);setCheckingBrand(b.id);setMsg("⏳ Vérification Facebook "+b.name+" en cours…");try{const r=await fetch("/api/admin/facebook-monitor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({brandId:b.id})});const x=await r.json();const d=x.diagnostic;if(!r.ok)setMsg("✕ "+(x.error||"Vérification impossible"));else setMsg("✓ "+b.name+" : "+x.records+" publication(s) reçue(s) de Bright Data, "+x.imported+" importée(s) dans Bikéo"+(d?" · "+d.duplicates+" doublon(s), "+d.invalid+" invalide(s)":""));if(r.ok&&x.imported>0)setTimeout(()=>location.reload(),3500)}catch(e:any){setMsg("✕ Vérification impossible : "+(e?.message||"erreur réseau"))}finally{setBusy(false);setCheckingBrand(null)}}
 async function epos(files:FileList|null){if(!files?.length)return;setBusy(true);for(const file of Array.from(files)){const fd=new FormData();fd.append("brand_id",brandId);fd.append("model_year",year);fd.append("file",file);const r=await fetch("/api/admin/brand-source",{method:"POST",body:fd});if(!r.ok){setBusy(false);return alert((await r.json()).error)}}setBusy(false);location.reload()}
 async function importSource(id:string){setBusy(true);const {data,error}=await s.functions.invoke("import-brand-epos",{body:{source_id:id}});setBusy(false);if(error||data?.error)alert(data?.error||error?.message);else location.reload()}
 async function addFeed(){if(!sourceUrl.trim())return;await s.from("brand_sources").insert({brand_id:brandId,source_type:sourceType,label:sourceType.toUpperCase()+" "+year,source_url:sourceUrl.trim(),model_year:Number(year),status:"configured"});location.reload()}
 async function moderate(id:string,action:string,cap?:string){await fetch("/api/admin/brand-content/moderate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,caption:cap})});location.reload()}
 async function createPhotoPost(photo:any){const st=stores.find((x:any)=>x.id===photo.store_id);if(!st)return;const type=photoTheme[photo.id]||"livraison";const {error}=await s.from("social_posts").insert({source_type:"store",store_id:st.id,template_type:type,title:themeLabels[type],caption:caption(type,st),media_urls:[photo.url],status:"draft"});if(error)alert(error.message);else{await s.from("social_photos").update({status:"archived",archived_at:new Date().toISOString()}).eq("id",photo.id);location.reload()}}
 async function saveDraft(){await s.from("platform_settings").update({site_editor_draft:siteDraft,updated_at:new Date().toISOString()}).eq("id",1);setMsg("✓ Brouillon enregistré")}
 async function publishSite(){const note=prompt("Message affiché aux magasins à leur prochaine connexion :","Le site personnalisable Bikéo a évolué.");if(note===null)return;await s.from("platform_settings").update({site_editor_draft:siteDraft,site_editor_published:siteDraft,site_release_version:Number(platformSettings.site_release_version||0)+1,site_release_note:note,site_released_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",1);setMsg("✓ Version publiée pour tous les magasins");location.reload()}
 const head=tab==="overview"?"Pilotage Bikéo":tab==="stores"?"Magasins partenaires":tab==="brands"?"Marques partenaires":tab==="data"?"EPOS & flux":tab==="qr"?"Lots PLV":tab==="community"?"Community Management":"Site par défaut";
 return <main className={styles.admin}><aside><div className={styles.brand}>{platformSettings.logo_rectangle_url?<img src={platformSettings.logo_rectangle_url} alt="Bikéo"/>:<b>bikéo</b>}<span>ADMIN</span></div>{nav.map(([k,l])=><button key={k} className={tab===k?styles.active:""} onClick={()=>goto(k)}>{l}</button>)}<a href="/dashboard">← Espace magasin</a></aside><section className={styles.main}><header><small>SUPERADMIN BIKÉO</small><h1>{head}</h1><p>Le cockpit central pour piloter les magasins, les marques, les contenus et les outils Bikéo.</p></header>{msg&&<div className={styles.message}>{msg}</div>}
 {tab==="overview"&&<><div className={styles.logoBar}><div><b>Identité Bikéo</b><span>Logos plateforme</span></div>{platformSettings.logo_rectangle_url&&<img src={platformSettings.logo_rectangle_url}/>}<label>Rectangle<input type="file" accept="image/*,.svg" onChange={e=>e.target.files?.[0]&&uploadPlatform("rectangle",e.target.files[0])}/></label><label>Carré<input type="file" accept="image/*,.svg" onChange={e=>e.target.files?.[0]&&uploadPlatform("square",e.target.files[0])}/></label></div><div className={styles.kpis}>
  <button onClick={()=>goto("stores")}><strong>{stores.length}</strong><b>Magasins</b><span>{stores.filter((x:any)=>x.account_status!=="paused").length} actifs · {stores.filter((x:any)=>!x.onboarding_completed_at).length} onboarding à terminer</span></button>
  <button onClick={()=>goto("brands")}><strong>{brands.length}</strong><b>Marques</b><span>{products.length} produits · {socialMonitors.filter((x:any)=>x.enabled).length} sources sociales actives</span></button>
  <button onClick={()=>goto("data")}><strong>{sources.length}</strong><b>EPOS & flux</b><span>{sourceYears.length} millésime(s) · {sources.filter((x:any)=>x.status==="pending").length} à traiter</span></button>
  <button onClick={()=>goto("community")}><strong>{pending.length}</strong><b>À valider</b><span>{availablePhotos.length} photos magasins · {availableBrands.length} contenus marques</span></button>
  <button onClick={()=>goto("qr")}><strong>{qrBatches.length}</strong><b>Lots PLV</b><span>{configuredPlv} PLV attribuées</span></button>
  <button onClick={()=>goto("site")}><strong>v{platformSettings.site_release_version||0}</strong><b>Site par défaut</b><span>{platformSettings.site_released_at?"Publié le "+new Date(platformSettings.site_released_at).toLocaleDateString("fr-FR"):"Aucune version publiée"}</span></button>
 </div></>}
 {tab==="stores"&&<><div className={styles.toolbar}><div><b>{stores.length} magasins</b><span>Vue compacte : activité, marques, site et accès en un coup d’œil.</span></div></div><div className={styles.storeList}>{stores.map((x:any)=><AdminStoreCrmCard key={x.id} store={x} access={accessStatus.find((z:any)=>z.store_id===x.id)} brandCount={brandCount(x.id)} productCount={storeBrands.filter((sb:any)=>sb.store_id===x.id).reduce((n:number,sb:any)=>n+products.filter((pr:any)=>pr.brand_id===sb.brand_id).length,0)}/>)}</div></>}
 {tab==="brands"&&<><div className={styles.toolbar}><input placeholder="Nouvelle marque Bikéo" value={brandName} onChange={e=>setBrandName(e.target.value)}/><button onClick={addBrand}>＋ Créer la marque</button></div><div className={styles.brandList}>{[...brands].sort((a:any,b:any)=>storeCount(b.id)-storeCount(a.id)).map((b:any)=>{const open=openBrand===b.id,m=socialMonitors.find((x:any)=>x.brand_id===b.id),pc=products.filter((x:any)=>x.brand_id===b.id).length;return <article key={b.id}><button className={styles.brandRow} onClick={()=>setOpenBrand(open?null:b.id)}><span className={styles.brandLogo}>{b.logo_url?<img src={b.logo_url}/>:b.name.slice(0,2)}</span><b>{b.name}</b><span>{pc} produits</span><span>{storeCount(b.id)} magasin{storeCount(b.id)>1?"s":""}</span><span className={m?.enabled?styles.ok:styles.muted}>{m?.enabled?"Facebook actif":"Social en pause"}</span><i>{open?"−":"+"}</i></button>{open&&<div className={styles.brandDetail}><section><h3>Identité & accès marque</h3><label>Logo officiel<input type="file" accept="image/*,.svg" onChange={e=>e.target.files?.[0]&&brandLogo(b,e.target.files[0])}/></label><button onClick={()=>inviteBrand(b)}>Générer le lien d’activation</button>{brandInvite[b.id]&&<input readOnly value={brandInvite[b.id]}/>}</section><section><h3>Collecte Facebook</h3><input id={"fb-"+b.id} defaultValue={m?.facebook_page_url||""} placeholder="URL Facebook"/><div><button onClick={()=>saveMonitor(b,(document.getElementById("fb-"+b.id) as HTMLInputElement)?.value||"",m?.enabled??false)}>Enregistrer</button><button onClick={()=>saveMonitor(b,(document.getElementById("fb-"+b.id) as HTMLInputElement)?.value||"",!m?.enabled)}>{m?.enabled?"Mettre en pause":"Activer"}</button>{m?.facebook_page_url&&<button disabled={checkingBrand===b.id} onClick={()=>checkMonitor(b)}>{checkingBrand===b.id?"Vérification en cours…":"Vérifier maintenant"}</button>}</div>{m?.last_checked_at&&<small>Dernière vérification : {new Date(m.last_checked_at).toLocaleString("fr-FR")}</small>}</section></div>}</article>})}</div></>}
 {tab==="data"&&<><div className={styles.dataAdd}><h2>Ajouter des données marque</h2><div><select value={brandId} onChange={e=>setBrandId(e.target.value)}>{brands.map((b:any)=><option value={b.id} key={b.id}>{b.name}</option>)}</select><input type="number" value={year} onChange={e=>setYear(e.target.value)}/></div><label><b>EPOS / catalogue marque</b><span>PDF, CSV ou XLSX · plusieurs fichiers possibles</span><input multiple type="file" accept=".pdf,.csv,.xls,.xlsx" onChange={e=>epos(e.target.files)}/></label><div><select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="ftp">FTP</option><option value="sftp">SFTP</option><option value="api">API</option><option value="url">URL</option></select><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="URL ou adresse du flux"/><button onClick={addFeed}>Ajouter</button></div></div><div className={styles.filterBar}><b>Sources enregistrées</b><select value={dataBrand} onChange={e=>setDataBrand(e.target.value)}><option value="all">Toutes les marques</option>{brands.map((b:any)=><option value={b.id} key={b.id}>{b.name}</option>)}</select><select value={dataYear} onChange={e=>setDataYear(e.target.value)}><option value="all">Toutes les années</option>{sourceYears.map((y:any)=><option key={y}>{y}</option>)}</select><span>{filteredSources.length} source(s)</span></div><div className={styles.sourceList}>{filteredSources.map((x:any)=><article key={x.id}><b>{brands.find((b:any)=>b.id===x.brand_id)?.name||"Marque"}</b><span>{x.model_year||"—"}</span><span>{x.label||x.source_type}</span><code>{x.file_name||x.source_url||"—"}</code><em>{x.status==="imported"?"Importé · "+(x.imported_products||0)+" produits":x.status}</em>{x.source_type==="epos_file"&&String(x.file_name||"").toLowerCase().endsWith(".csv")&&<button onClick={()=>importSource(x.id)}>{x.status==="imported"?"Réimporter":"Importer"}</button>}</article>)}</div></>}
 {tab==="qr"&&<AdminQrPanel stores={stores} batches={qrBatches} platformSettings={platformSettings}/>}
 {tab==="community"&&<><div className={styles.communityKpis}><article><strong>{pending.length}</strong><b>À valider</b><span>Posts détectés automatiquement</span></article><article><strong>{availablePhotos.length}</strong><b>Photos magasins</b><span>Matière à transformer en posts</span></article><article><strong>{availableBrands.length}</strong><b>Contenus marques</b><span>Validés et disponibles</span></article><article><strong>{socialPosts.filter((x:any)=>x.source_type==="store").length}</strong><b>Posts magasins</b><span>Créés depuis Bikéo</span></article></div><BrandContentImporter brands={brands}/>
  <section className={styles.fold}><button onClick={()=>setSections(v=>({...v,validate:!v.validate}))}><span><small>API / SCRAPING</small><b>À valider · {pending.length}</b></span><i>{sections.validate?"−":"+"}</i></button>{sections.validate&&<div className={styles.feed}>{pending.map((x:any)=><article key={x.id}>{x.media_urls?.[0]&&<img src={x.media_urls[0]}/>}<div><small>{x.brands?.name||"MARQUE"} · {x.source_network||"WEB"}</small><b>{x.title||"Publication détectée"}</b><p>{x.original_caption}</p><footer><button onClick={()=>moderate(x.id,"ignore")}>Ignorer</button><button onClick={()=>moderate(x.id,"approve",x.original_caption)}>Valider</button></footer></div></article>)}</div>}</section>
  <section className={styles.fold}><button onClick={()=>setSections(v=>({...v,photos:!v.photos}))}><span><small>BIBLIOTHÈQUE MAGASINS</small><b>Photos à transformer · {availablePhotos.length}</b></span><i>{sections.photos?"−":"+"}</i></button>{sections.photos&&<div className={styles.photoGrid}>{availablePhotos.map((ph:any)=>{const st=stores.find((x:any)=>x.id===ph.store_id);return <article key={ph.id}><img src={ph.url}/><b>{st?.name||"Magasin"}</b><select value={photoTheme[ph.id]||"livraison"} onChange={e=>setPhotoTheme(v=>({...v,[ph.id]:e.target.value}))}>{Object.entries(themeLabels).map(([k,l]:any)=><option value={k} key={k}>{l}</option>)}</select><p>{caption(photoTheme[ph.id]||"livraison",st)}</p><button onClick={()=>createPhotoPost(ph)}>Créer le brouillon</button></article>})}</div>}</section>
  <section className={styles.fold}><button onClick={()=>setSections(v=>({...v,created:!v.created}))}><span><small>BIBLIOTHÈQUE CENTRALE</small><b>Contenus créés · {created.length}</b></span><i>{sections.created?"−":"+"}</i></button>{sections.created&&<><div className={styles.filterBar}><select value={communityFilter} onChange={e=>setCommunityFilter(e.target.value as any)}><option value="all">Marques + magasins</option><option value="brand">Contenus marque</option><option value="store">Contenus magasin</option></select>{communityFilter!=="store"&&<select value={communityBrand} onChange={e=>setCommunityBrand(e.target.value)}><option value="all">Toutes les marques</option>{brands.map((b:any)=><option value={b.id} key={b.id}>{b.name}</option>)}</select>}{communityFilter!=="brand"&&<select value={communityStore} onChange={e=>setCommunityStore(e.target.value)}><option value="all">Tous les magasins</option>{stores.map((st:any)=><option value={st.id} key={st.id}>{st.name}</option>)}</select>}</div><div className={styles.feed}>{created.map((x:any)=><article key={(x._kind||"x")+x.id}>{x.media_urls?.[0]&&<img src={x.media_urls[0]}/>}<div><small>{x._kind==="brand"?"MARQUE":"MAGASIN"}</small><b>{x.title||"Publication"}</b><p>{x.original_caption||x.caption}</p></div></article>)}</div></>}</section></>}
 {tab==="site"&&<><div className={styles.siteHero}><div><small>ÉDITEUR GLOBAL</small><h2>Le modèle commun à tous les sites magasins</h2><p>Travaille ici en brouillon. Rien ne change côté magasins tant que tu ne publies pas la nouvelle version.</p></div><div><span>Version publiée</span><strong>v{platformSettings.site_release_version||0}</strong><small>{platformSettings.site_released_at?new Date(platformSettings.site_released_at).toLocaleString("fr-FR"):"Jamais publiée"}</small></div></div><div className={styles.siteEditor}><section><h3>Fonctionnalités visibles</h3>{[["catalogue","Catalogue vélos"],["advisor","Conseiller un client"],["loyalty","Fidélité Wallet"],["social","Réseaux sociaux"],["plv","PLV & QR"],["leads","Leads clients"]].map(([k,l])=><label key={k}><input type="checkbox" checked={siteDraft[k]!==false} onChange={e=>setSiteDraft((v:any)=>({...v,[k]:e.target.checked}))}/><span><b>{l}</b><small>Disponible sur les sites personnalisables</small></span></label>)}</section><section><h3>Réglages du modèle</h3><label>Titre d’accueil par défaut<input value={siteDraft.hero_title||""} placeholder="Ton magasin vélo" onChange={e=>setSiteDraft((v:any)=>({...v,hero_title:e.target.value}))}/></label><label>Texte d’introduction<textarea value={siteDraft.hero_text||""} placeholder="Conseil, atelier et vélos sélectionnés…" onChange={e=>setSiteDraft((v:any)=>({...v,hero_text:e.target.value}))}/></label><label>Nombre de vélos mis en avant<input type="number" min="1" max="12" value={siteDraft.featured_count||4} onChange={e=>setSiteDraft((v:any)=>({...v,featured_count:Number(e.target.value)}))}/></label></section></div><footer className={styles.siteActions}><button onClick={saveDraft}>Enregistrer le brouillon</button><button className={styles.publish} onClick={publishSite}>Publier pour tous les magasins</button></footer>{platformSettings.site_release_note&&<div className={styles.release}><b>Dernière évolution communiquée aux magasins</b><p>{platformSettings.site_release_note}</p></div>}</>}
 </section></main>
}