"use client";
import {useMemo,useState} from "react";import Link from "next/link";import LeadForm from "./LeadForm";
type Bike={id:string;slug:string;name:string;brand:string;category:string|null;motor:string|null;price:number|null;status:string;qty:number};
export default function Advisor({bikes}:{bikes:Bike[]}){const [mode,setMode]=useState<"home"|"needs"|"search">("home");const [step,setStep]=useState(0);const [answers,setAnswers]=useState<string[]>([]);const [q,setQ]=useState("");
 const questions=[["Où voulez-vous rouler ?",["Route","Routes et chemins","Montagne / sentiers","Ville / quotidien"]],["Avec ou sans assistance électrique ?",["Électrique","Sans assistance","Peu importe"]],["Quel type de sorties ?",["Sport / performance","Loisir","Aventure / longues sorties","Quotidien"]],["Quel terrain domine ?",["Roulant","Mixte","Technique / engagé"]],["Votre priorité ?",["Confort","Polyvalence","Performance","Autonomie"]],["Quel budget ?",["Moins de 3 500 €","3 500 à 6 000 €","6 000 à 9 000 €","9 000 € et +"]]] as const;
 function score(b:Bike){let s=b.status==="in_stock"?5:b.status==="orderable"?2:0;const a=answers.join(" ").toLowerCase();const txt=(b.category+" "+b.motor+" "+b.name).toLowerCase();if(a.includes("montagne")&&(txt.includes("vtt")||txt.includes("trail")))s+=5;if(a.includes("route")&&txt.includes("route"))s+=5;if(a.includes("chemins")&&txt.includes("gravel"))s+=5;if(a.includes("électrique")&&b.motor)s+=5;if(a.includes("sans assistance")&&!b.motor)s+=5;const p=(b.price??0)/100;if(a.includes("moins de 3 500")&&p<3500)s+=3;if(a.includes("3 500 à 6 000")&&p>=3500&&p<6000)s+=3;if(a.includes("6 000 à 9 000")&&p>=6000&&p<9000)s+=3;if(a.includes("9 000")&&p>=9000)s+=3;return s}
 const results=useMemo(()=>[...bikes].sort((a,b)=>score(b)-score(a)).slice(0,3),[answers,bikes]);const found=useMemo(()=>{const x=q.toLowerCase().trim();return x?bikes.filter(b=>(b.brand+" "+b.name+" "+(b.motor??"")+" "+(b.category??"")).toLowerCase().includes(x)).slice(0,8):[]},[q,bikes]);
 if(mode==="home")return <><div className="advisorIntro"><p>CONSEILLER UN CLIENT</p><h1>Comment voulez-vous<br/>commencer ?</h1><span>Deux façons de trouver le bon vélo, reliées au catalogue et à la disponibilité du magasin.</span></div><div className="choiceGrid"><article><b>01</b><div className="choiceIcon">✦</div><h2>Trouver le vélo adapté</h2><p>6 questions simples sur la pratique, le terrain et le budget.</p><button onClick={()=>setMode("needs")}>Commencer →</button></article><article><b>02</b><div className="choiceIcon">⌕</div><h2>Je connais déjà un vélo</h2><p>Rechercher un vélo présent dans le catalogue du magasin.</p><button onClick={()=>setMode("search")}>Rechercher →</button></article></div></>;
 if(mode==="search")return <div className="advisorIntro advisorWide"><button onClick={()=>setMode("home")}>← Retour</button><p>RECHERCHE DIRECTE</p><h1>Quel vélo cherchez-vous ?</h1><input className="advisorSearch" autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex. Wild, Rise, Avinox, gravel..."/><div className="advisorResults">{found.map(b=><BikeCard key={b.id} b={b}/>)}</div></div>;
 const done=step>=questions.length;if(done){const top=results[0];return <div className="advisorIntro advisorWide"><button onClick={()=>{setStep(0);setAnswers([])}}>← Recommencer</button><p>RECOMMANDATIONS</p><h1>Les vélos les plus cohérents.</h1><span>Résultat basé sur les réponses et la disponibilité actuelle du magasin.</span><div className="advisorResults">{results.map((b,i)=><div key={b.id}><small>CHOIX {i+1}</small><BikeCard b={b}/></div>)}</div>{top&&<LeadForm productId={top.id} productName={top.name} source="advisor" prefillMessage={"Conseil Advisor — réponses : "+answers.join(" / ")}/>}</div>}
 const [question,opts]=questions[step];return <div className="advisorIntro" style={{maxWidth:850}}><p>QUESTION {step+1} / 6</p><h1>{question}</h1><div className="answerGrid">{opts.map(o=><button key={o} onClick={()=>{setAnswers([...answers,o]);setStep(step+1)}}>{o}<span>→</span></button>)}</div><button className="advisorBack" onClick={()=>step?(setStep(step-1),setAnswers(answers.slice(0,-1))):setMode("home")}>← Retour</button></div>}
function BikeCard({b}:{b:Bike}){const price=b.price==null?"Prix sur demande":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(b.price/100);return <Link className="advisorBike" href={"/magasin/demo/velos/"+b.slug}><div><small>{b.brand.toUpperCase()}</small><h3>{b.name}</h3><p>{[b.category,b.motor].filter(Boolean).join(" · ")}</p></div><div><em className={b.status==="in_stock"?"ok":"wait"}>{b.status==="in_stock"?"En stock":b.status==="orderable"?"Sur commande":"Indisponible"}</em><strong>{price}</strong></div></Link>}
