"use client";
import {useMemo,useState} from "react";import Link from "next/link";import LeadForm from "./LeadForm";
type Bike={id:string;slug:string;name:string;brand:string;category:string|null;motor:string|null;price:number|null;status:string;qty:number;image?:string|null};
const practice=(b:Bike)=>{const x=((b.category||"")+" "+b.name).toUpperCase();if(/ORCA|AVANT|ORDU/.test(x))return"Route";if(/TERRA/.test(x))return"Gravel";if(/CARPE|DIEM|KEMEN|MUGA|KIMU|VECTOR/.test(x))return"Ville";if(/WILD|OIZ|OCCAM|RALLON|ALMA|ONNA|LAUFEY|URRUN/.test(x))return"VTT";return"Autre"};
export default function Advisor({bikes,storeSlug="cycles-omega"}:{bikes:Bike[];storeSlug?:string}){const[mode,setMode]=useState<"home"|"needs"|"search">("home"),[step,setStep]=useState(0),[answers,setAnswers]=useState<string[]>([]),[q,setQ]=useState("");const questions=[["Où voulez-vous rouler ?",["Route","Routes et chemins","Montagne / sentiers","Ville / quotidien"]],["Avec ou sans assistance électrique ?",["Électrique","Sans assistance","Peu importe"]],["Quel type de sorties ?",["Sport / performance","Loisir","Aventure / longues sorties","Quotidien"]],["Quel terrain domine ?",["Roulant","Mixte","Technique / engagé"]],["Votre priorité ?",["Confort","Polyvalence","Performance","Autonomie"]],["Quel budget ?",["Moins de 3 500 €","3 500 à 6 000 €","6 000 à 9 000 €","9 000 € et +"]]] as const;
function score(b:Bike){let s=b.status==="in_stock"?4:b.status==="orderable"?2:0,a=answers.join(" ").toLowerCase(),p=practice(b),x=((b.category||"")+" "+b.name).toLowerCase();if(a.includes("montagne")&&p==="VTT")s+=9;if(a.includes("route")&&!a.includes("chemins")&&p==="Route")s+=9;if(a.includes("chemins")&&p==="Gravel")s+=9;if(a.includes("ville")&&p==="Ville")s+=9;if(a.includes("technique")&&/wild|occam|rallon|laufey/.test(x))s+=4;if(a.includes("performance")&&/oiz|orca|terra race|ordu|alma/.test(x))s+=4;if(a.includes("aventure")&&/terra|kemen|urrun/.test(x))s+=4;if(a.includes("quotidien")&&p==="Ville")s+=4;if(a.includes("autonomie")&&b.motor)s+=3;if(a.includes("électrique")&&b.motor)s+=8;if(a.includes("sans assistance")&&!b.motor)s+=8;if(a.includes("électrique")&&!b.motor)s-=8;if(a.includes("sans assistance")&&b.motor)s-=8;const z=(b.price??0)/100;if(a.includes("moins de 3 500")&&z&&z<3500)s+=4;if(a.includes("3 500 à 6 000")&&z>=3500&&z<6000)s+=4;if(a.includes("6 000 à 9 000")&&z>=6000&&z<9000)s+=4;if(a.includes("9 000")&&z>=9000)s+=4;return s}
const results=useMemo(()=>[...bikes].sort((a,b)=>score(b)-score(a)).slice(0,3),[answers,bikes]),found=useMemo(()=>{const x=q.toLowerCase().trim();return x?bikes.filter(b=>(b.brand+" "+b.name+" "+(b.motor||"")+" "+(b.category||"")).toLowerCase().includes(x)).slice(0,12):[]},[q,bikes]);
if(mode==="home")return <><div className="advisorIntro"><p>CONSEILLER UN CLIENT</p><h1>Comment voulez-vous<br/>commencer ?</h1><span>Le conseiller travaille directement avec le catalogue réel des marques distribuées par le magasin.</span></div><div className="choiceGrid"><article><b>01</b><div className="choiceIcon">✦</div><h2>Trouver le vélo adapté</h2><p>6 questions pour croiser pratique, assistance, terrain, priorité et budget.</p><button onClick={()=>setMode("needs")}>Commencer →</button></article><article><b>02</b><div className="choiceIcon">⌕</div><h2>Je connais déjà un vélo</h2><p>Recherche instantanée dans les modèles EPOS du magasin.</p><button onClick={()=>setMode("search")}>Rechercher →</button></article></div></>;
if(mode==="search")return <div className="advisorIntro advisorWide"><button onClick={()=>setMode("home")}>← Retour</button><p>RECHERCHE CATALOGUE</p><h1>Quel vélo cherchez-vous ?</h1><input className="advisorSearch" autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex. Wild LT, Orca, Terra..."/><div className="advisorResults">{found.map(b=><BikeCard key={b.id} b={b} storeSlug={storeSlug}/>)}</div></div>;
if(step>=questions.length){const top=results[0];return <div className="advisorIntro advisorWide"><button onClick={()=>{setStep(0);setAnswers([])}}>← Recommencer</button><p>SÉLECTION PERSONNALISÉE</p><h1>Les modèles les plus cohérents.</h1><span>Sélection basée sur vos réponses, les familles EPOS, la motorisation, le budget et la disponibilité du magasin.</span><div className="advisorResults">{results.map((b,i)=><div key={b.id}><small>{i===0?"RECOMMANDATION PRINCIPALE":`ALTERNATIVE ${i}`}</small><BikeCard b={b} storeSlug={storeSlug}/></div>)}</div>{top&&<LeadForm storeSlug={storeSlug} productId={top.id} productName={top.name} source="advisor" prefillMessage={"Conseil Bikéo — "+answers.join(" / ")}/>}</div>}
const[question,opts]=questions[step];return <div className="advisorIntro" style={{maxWidth:850}}><p>QUESTION {step+1} / 6</p><h1>{question}</h1><div className="answerGrid">{opts.map(o=><button key={o} onClick={()=>{setAnswers([...answers,o]);setStep(step+1)}}>{o}<span>→</span></button>)}</div><button className="advisorBack" onClick={()=>step?(setStep(step-1),setAnswers(answers.slice(0,-1))):setMode("home")}>← Retour</button></div>}
function BikeCard({b,storeSlug}:{b:Bike;storeSlug:string}){const price=b.price==null?"Prix sur demande":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(b.price/100);return <Link className="advisorBike smartBike" href={"/magasin/"+storeSlug+"/velos/"+b.slug}>{b.image&&<img src={b.image} alt=""/>}<div><small>{b.brand.toUpperCase()} · {practice(b)}</small><h3>{b.name}</h3><p>{[b.category,b.motor].filter(Boolean).join(" · ")}</p></div><div><em className={b.status==="in_stock"?"ok":"wait"}>{b.status==="in_stock"?"En stock":b.status==="orderable"?"Sur commande":"Catalogue"}</em><strong>{price}</strong></div></Link>}