"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "../lib/supabase/client";
export default function LoginForm(){const router=useRouter();const[mode,setMode]=useState<"login"|"signup">("login");const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget),email=String(f.get("email")||"").trim(),password=String(f.get("password")||""),invite=String(f.get("invite")||"").trim();const supabase=createClient();
if(mode==="signup"){const{data,error}=await supabase.auth.signUp({email,password});if(error){setMsg("Création impossible : "+error.message);setBusy(false);return}if(!data.session){setMsg("Compte créé mais une confirmation email est encore demandée.");setBusy(false);return}const{error:claimError}=await supabase.rpc("claim_store_invite",{p_token:invite});if(claimError){setMsg("Compte créé, mais rattachement magasin impossible : "+claimError.message);setBusy(false);return}}
else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error){setMsg("Connexion impossible : "+error.message);setBusy(false);return}}
router.replace("/dashboard");router.refresh()}
return <form className="loginCard" onSubmit={submit}><div className="advisorLogo">bik<span>é</span>o</div><small>ESPACE MAGASIN</small><h1>{mode==="signup"?"Créer mon compte":"Connexion"}</h1><p>{mode==="signup"?"Première connexion à ton magasin Bikéo.":"Accède à ton espace magasin."}</p><label>Email<input required name="email" type="email" autoComplete="email"/></label><label>Mot de passe<input required name="password" type="password" minLength={6} autoComplete={mode==="signup"?"new-password":"current-password"}/></label>{mode==="signup"&&<label>Code d'invitation<input required name="invite" autoComplete="off"/></label>}<button className="primaryBtn" disabled={busy}>{busy?"Patiente...":mode==="signup"?"Créer mon compte magasin":"Se connecter"}</button>{msg&&<p className="formError">{msg}</p>}<button type="button" className="authSwitch" onClick={()=>{setMode(mode==="signup"?"login":"signup");setMsg("")}}>{mode==="signup"?"J'ai déjà un compte → Se connecter":"Première connexion → Créer mon compte"}</button></form>}