"use client";
import {useState,type FormEvent} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {createClient} from "../lib/supabase/client";
export default function LoginForm({logoUrl="",hasSession=false}:{logoUrl?:string;hasSession?:boolean}){const router=useRouter(),search=useSearchParams(),activation=search.get("activation")||"";const[mode,setMode]=useState<"login"|"signup">(activation?"signup":"login");const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
async function leaveSession(){const s=createClient();await s.auth.signOut();location.reload()}
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget),email=String(f.get("email")||"").trim(),password=String(f.get("password")||""),invite=String(f.get("invite")||"").trim();const supabase=createClient();
if(mode==="signup"){const{data:valid,error:validationError}=await supabase.rpc("validate_store_invite",{p_token:invite});if(validationError||!valid){setMsg("Ce lien d’activation est invalide ou a expiré. Demande un nouvel accès à Bikéo.");setBusy(false);return}const{data,error}=await supabase.auth.signUp({email,password});if(error){setMsg("Création impossible : "+error.message);setBusy(false);return}if(!data.session){setMsg("Compte créé mais une confirmation email est encore demandée.");setBusy(false);return}const{error:claimError}=await supabase.rpc("claim_store_invite",{p_token:invite});if(claimError){setMsg("Compte créé, mais rattachement magasin impossible : "+claimError.message);setBusy(false);return}}
else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error){setMsg("Connexion impossible : "+error.message);setBusy(false);return}}
router.replace("/dashboard");router.refresh()}
return <form className="loginCard" onSubmit={submit}><div className="advisorLogo">{logoUrl?<img className="platformLogo loginPlatformLogo" src={logoUrl} alt="Bikéo"/>:<>bik<span>é</span>o</>}</div><small>ESPACE MAGASIN</small><h1>{mode==="signup"?"Activer mon accès":"Connexion"}</h1><p>{mode==="signup"?"Active l’accès au magasin qui t’a été attribué par Bikéo.":"Accède à ton espace magasin."}</p>{activation&&hasSession&&<div className="activationSessionNotice"><b>Une autre session Bikéo est ouverte sur ce navigateur.</b><span>Déconnecte-la pour activer ce nouveau magasin sans mélanger les comptes.</span><button type="button" className="authSwitch" onClick={leaveSession}>Déconnecter la session actuelle</button></div>}<label>Email<input required name="email" type="email" autoComplete="email"/></label><label>Mot de passe<input required name="password" type="password" minLength={6} autoComplete={mode==="signup"?"new-password":"current-password"}/></label>{mode==="signup"&&<label>Code d’invitation<input required name="invite" defaultValue={activation} readOnly={!!activation} autoComplete="off"/></label>}<button className="primaryBtn" disabled={busy||(!!activation&&hasSession)}>{busy?"Patiente...":mode==="signup"?"Activer mon accès":"Se connecter"}</button>{msg&&<p className="formError">{msg}</p>}<button type="button" className="authSwitch" onClick={()=>{setMode(mode==="signup"?"login":"signup");setMsg("")}}>{mode==="signup"?"J'ai déjà un compte → Se connecter":"Première connexion · Activer mon accès"}</button></form>}