"use client";
import {useEffect,useMemo,useState} from "react";
const tabs=[["overview","Vue d’ensemble"],["card","Ma carte"],["program","Programme fidélité"],["customers","CRM clients"],["scan","Scanner"],["notifications","Notifications"],["share","Partager"]] as const;
type Customer={id:string;firstName?:string;lastName?:string;email?:string;phone?:string;memberId?:string;points?:number;stamps?:number;rewardsAvailable?:number;walletType?:string;lastVisitAt?:string};
type DigifydData={cardDesign?:Record<string,any>;loyalty?:Record<string,any>;customers?:Customer[];notifications?:any[];business?:Record<string,any>};
export default function LoyaltyWorkspace(){
 const[tab,setTab]=useState<(typeof tabs)[number][0]>("overview"),[integration,setIntegration]=useState<any>(null),[data,setData]=useState<DigifydData|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const load=()=>{fetch("/api/loyalty/status",{cache:"no-store"}).then(r=>r.json()).then(x=>setIntegration(x.integration??null));fetch("/api/loyalty/data",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"Digifyd indisponible");setData(x.data||{})}).catch(e=>setError(e.message))};useEffect(load,[]);
 const customers=data?.customers||[],wallets=customers.filter(x=>x.walletType&&x.walletType!=="none").length,rewards=customers.reduce((n,x)=>n+(x.rewardsAvailable||0),0);
 const save=async(patch:Partial<DigifydData>)=>{setSaving(true);setError("");try{const r=await fetch("/api/loyalty/data",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});const x=await r.json();if(!r.ok)throw new Error(x.error||"Enregistrement impossible");setData(x.data)}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}};
 return <div className="loyaltyWorkspace">
 <header className="dashHeader"><div><p className="dashEyebrow">FIDÉLITÉ BIKÉO · MOTEUR DIGIFYD</p><h1>Fidélité & Wallet</h1><p>Carte Apple Wallet et Google Wallet, programme fidélité, clients et communication depuis Bikéo.</p></div><span className={"loyaltyStatus "+(integration?.status==="active"||integration?.status==="provisioned"?"connected":"")}>{integration?.status==="active"||integration?.status==="provisioned"?"Moteur Digifyd provisionné":"Connexion Digifyd à finaliser"}</span></header>
 {error&&<div className="loyaltyAlert">{error}</div>}<nav className="loyaltyTabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"on":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="overview"&&<section><div className="statGrid"><Stat n={customers.length} l="Clients fidélité" s="CRM Digifyd"/><Stat n={wallets} l="Cartes Wallet" s="Apple + Google"/><Stat n={rewards} l="Récompenses" s="disponibles"/><Stat n={data?.notifications?.length||0} l="Notifications" s="campagnes"/></div><div className="loyaltyGrid"><Feature title="Ma carte" text="Logo, bannière, couleurs et informations Wallet." action={()=>setTab("card")}/><Feature title="Programme fidélité" text="Points, tampons, seuils et récompenses." action={()=>setTab("program")}/><Feature title="CRM clients" text="Membres, Wallet, progression et dernière visite." action={()=>setTab("customers")}/><Feature title="Notifications Wallet" text="Campagnes et communication sur les cartes." action={()=>setTab("notifications")}/></div></section>}
 {tab==="card"&&<CardEditor value={data?.cardDesign||{}} saving={saving} onSave={v=>save({cardDesign:v})}/>}
 {tab==="program"&&<ProgramEditor value={data?.loyalty||{}} saving={saving} onSave={v=>save({loyalty:v})}/>}
 {tab==="customers"&&<section className="loyaltyPanel"><small>CRM DIGIFYD</small><h2>Clients fidélité <em>{customers.length}</em></h2>{customers.length?<div className="loyaltyTable">{customers.map(c=><div className="loyaltyCustomer" key={c.id}><div><strong>{c.firstName} {c.lastName}</strong><span>{c.memberId} · {c.phone||c.email||"—"}</span></div><b>{(data?.loyalty?.type==="points"?c.points:c.stamps)||0} {data?.loyalty?.type==="points"?"pts":"tampons"}</b><span className={"walletBadge "+(c.walletType||"none")}>{c.walletType||"none"}</span><time>{c.lastVisitAt?new Date(c.lastVisitAt).toLocaleDateString("fr-FR"):"—"}</time></div>)}</div>:<p>Aucun client pour le moment.</p>}</section>}
 {tab==="scan"&&<Panel eyebrow="PASSAGE EN MAGASIN" title="Scanner une carte" text="Le scanner Digifyd sera raccordé ici pour identifier le membre, créditer ou retirer la fidélité et actualiser son Wallet."/>}
 {tab==="notifications"&&<Panel eyebrow="COMMUNICATION WALLET" title="Notifications" text="Les campagnes Digifyd, audiences, envois Wallet, programmations et historique seront pilotés ici."/>}
 {tab==="share"&&<Panel eyebrow="ACQUISITION" title="Partager la carte" text={"Le lien public Digifyd du magasin est provisionné : "+(integration?.external_slug||"—")+". QR code et parcours Apple/Google seront intégrés ici."}/>}
 </div>}
function Stat({n,l,s}:{n:number;l:string;s:string}){return <div className="statCard"><span>{l}</span><strong>{n}</strong><small>{s}</small></div>}
function Feature({title,text,action}:{title:string;text:string;action:()=>void}){return <article><small>DIGIFYD</small><h3>{title}</h3><p>{text}</p><button onClick={action}>Ouvrir →</button></article>}
function CardEditor({value,onSave,saving}:{value:Record<string,any>;onSave:(v:any)=>void;saving:boolean}){const[v,setV]=useState(value);useEffect(()=>setV(value),[value]);return <section className="loyaltyPanel"><small>PERSONNALISATION WALLET</small><h2>Ma carte</h2><div className="loyaltyForm"><label>Nom de la carte<input value={v.cardName||""} onChange={e=>setV({...v,cardName:e.target.value})}/></label><label>Description<input value={v.description||""} onChange={e=>setV({...v,description:e.target.value})}/></label><label>Logo URL<input value={v.logoUrl||""} onChange={e=>setV({...v,logoUrl:e.target.value})}/></label><label>Bannière URL<input value={v.bannerUrl||""} onChange={e=>setV({...v,bannerUrl:e.target.value})}/></label><label>Couleur carte<input type="color" value={v.backgroundColor||"#171a19"} onChange={e=>setV({...v,backgroundColor:e.target.value})}/></label><label>Couleur texte<input type="color" value={v.textColor||"#ffffff"} onChange={e=>setV({...v,textColor:e.target.value})}/></label><label>Couleur progression<input type="color" value={v.progressColor||"#eb7100"} onChange={e=>setV({...v,progressColor:e.target.value})}/></label><label>Téléphone<input value={v.phone||""} onChange={e=>setV({...v,phone:e.target.value})}/></label><label>Adresse<input value={v.address||""} onChange={e=>setV({...v,address:e.target.value})}/></label><label>Site web<input value={v.websiteUrl||""} onChange={e=>setV({...v,websiteUrl:e.target.value})}/></label></div><button className="loyaltySave" disabled={saving} onClick={()=>onSave(v)}>{saving?"Enregistrement…":"Enregistrer la carte"}</button></section>}
function ProgramEditor({value,onSave,saving}:{value:Record<string,any>;onSave:(v:any)=>void;saving:boolean}){const[v,setV]=useState(value);useEffect(()=>setV(value),[value]);return <section className="loyaltyPanel"><small>PROGRAMME DIGIFYD</small><h2>Programme fidélité</h2><div className="loyaltyForm"><label>Type<select value={v.type||"stamps"} onChange={e=>setV({...v,type:e.target.value})}><option value="stamps">Tampons</option><option value="points">Points</option></select></label>{v.type==="points"?<label>Seuil de points<input type="number" value={v.pointsMax||500} onChange={e=>setV({...v,pointsMax:+e.target.value})}/></label>:<label>Nombre de tampons<input type="number" value={v.stampsMax||8} onChange={e=>setV({...v,stampsMax:+e.target.value})}/></label>}<label>Récompense<input value={v.rewardLabel||""} onChange={e=>setV({...v,rewardLabel:e.target.value})}/></label><label>Type de récompense<select value={v.rewardType||"discount"} onChange={e=>setV({...v,rewardType:e.target.value})}><option value="discount">Remise</option><option value="free_item">Produit / service offert</option><option value="custom">Personnalisée</option></select></label><label className="check"><input type="checkbox" checked={v.carryOver!==false} onChange={e=>setV({...v,carryOver:e.target.checked})}/> Reporter le surplus après récompense</label><label className="check"><input type="checkbox" checked={v.showBarcode!==false} onChange={e=>setV({...v,showBarcode:e.target.checked})}/> Afficher le QR / code membre</label></div><button className="loyaltySave" disabled={saving} onClick={()=>onSave(v)}>{saving?"Enregistrement…":"Enregistrer le programme"}</button></section>}
function Panel({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <section className="loyaltyPanel"><small>{eyebrow}</small><h2>{title}</h2><p>{text}</p></section>}