"use client";
import {useMemo,useRef,useState,useEffect} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "../lib/supabase/client";

export default function QrConfigurator({qrs,bikes}:{qrs:any[];bikes:any[]}){
 const s=createClient(),router=useRouter();
 const[qr,setQr]=useState(""),[brand,setBrand]=useState(""),[product,setProduct]=useState(""),[search,setSearch]=useState(""),[scanning,setScanning]=useState(false),[origin,setOrigin]=useState("");
 const video=useRef<HTMLVideoElement>(null);
 useEffect(()=>setOrigin(window.location.origin),[]);
 const brands=useMemo(()=>Array.from(new Set(bikes.map(b=>b.brand))).sort() as string[],[bikes]);
 const filtered=useMemo(()=>{const list=brand?bikes.filter(b=>b.brand===brand):[];const q=search.trim().toLowerCase();return q?list.filter(b=>(b.name+" "+(b.year||"")).toLowerCase().includes(q)).slice(0,12):[]},[bikes,brand,search]);
 const target=qrs.find(x=>x.qr_number.toLowerCase()===qr.trim().toLowerCase());
 const selected=bikes.find(b=>b.id===product);
 async function save(){if(!target){alert("Ce numéro de QR n'appartient pas à ton magasin.");return}if(!product){alert("Choisis un vélo.");return}const{error}=await s.from("store_qr_codes").update({product_id:product,updated_at:new Date().toISOString()}).eq("id",target.id);if(error)alert(error.message);else{setQr("");setBrand("");setProduct("");setSearch("");router.refresh()}}
 async function scan(){const BD=(window as any).BarcodeDetector;if(!BD){alert("Le scan caméra n'est pas disponible sur ce navigateur. Tu peux saisir le numéro exact du QR.");return}try{setScanning(true);const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});if(video.current){video.current.srcObject=stream;await video.current.play()}const detector=new BD({formats:["qr_code"]});const timer=setInterval(async()=>{if(!video.current)return;const codes=await detector.detect(video.current);if(codes[0]?.rawValue){clearInterval(timer);stream.getTracks().forEach((t:any)=>t.stop());const raw=String(codes[0].rawValue);const match=qrs.find(x=>raw.includes(x.code)||raw.includes(x.qr_number));if(match)setQr(match.qr_number);else alert("QR non attribué à ce magasin.");setScanning(false)}},350)}catch{setScanning(false);alert("Impossible d'accéder à la caméra.")}}
 const scanUrl=target&&origin?origin+"/q/"+target.code:"";
 return <section className="panel merchantQrConfig"><div><small>CONFIGURER UNE ACCROCHE</small><h2>Scanner ou saisir le QR</h2><p>Scanne le support ou saisis son numéro, puis recherche directement le modèle à associer.</p>{scanUrl&&<div className="qrTestCard"><img src={"https://api.qrserver.com/v1/create-qr-code/?size=180x180&data="+encodeURIComponent(scanUrl)} alt={"QR "+target.qr_number}/><div><strong>{target.qr_number}</strong><span>QR de test</span><a href={scanUrl} target="_blank" rel="noreferrer">Tester le lien ↗</a></div></div>}</div><div className="qrConfigForm"><div className="qrNumberLine"><input value={qr} onChange={e=>setQr(e.target.value)} placeholder="N° QR exact · ex. 94D37-0001"/><button type="button" onClick={scan}>Scanner le QR</button></div>{scanning&&<video className="qrCamera" ref={video} muted playsInline/>}<select value={brand} onChange={e=>{setBrand(e.target.value);setProduct("");setSearch("")}}><option value="">1. Sélectionner la marque</option>{brands.map(b=><option key={b} value={b}>{b}</option>)}</select><div className="bikeSearchBox"><input value={search} disabled={!brand} onChange={e=>{setSearch(e.target.value);setProduct("")}} placeholder={brand?"2. Tape le nom du modèle · ex. Wild, Rise, Orca…":"2. Sélectionne d'abord la marque"}/>{brand&&search&&<div className="bikeSearchResults">{filtered.length?filtered.map(b=><button type="button" key={b.id} className={product===b.id?"selected":""} onClick={()=>{setProduct(b.id);setSearch(b.name+(b.year?" · "+b.year:""))}}><strong>{b.name}</strong>{b.year&&<span>{b.year}</span>}</button>):<span className="noBikeResult">Aucun modèle trouvé</span>}</div>}</div>{selected&&<div className="selectedBike">✓ {selected.brand} · <strong>{selected.name}</strong>{selected.year?" · "+selected.year:""}</div>}<button className="primaryBtn" type="button" onClick={save}>Associer ce QR au vélo</button></div></section>
}