"use client";import {useMemo,useState} from "react";import {createClient} from "../lib/supabase/client";
const slugify=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export default function SuperAdmin({stores,brands,sources,products}:{stores:any[];brands:any[];sources:any[];products:any[]}){
 const [tab,setTab]=useState("overview"),[busy,setBusy]=useState(false),[brandName,setBrandName]=useState(""),[storeName,setStoreName]=useState(""),[brandId,setBrandId]=useState(brands.find(b=>b.name==="Orbea")?.id||brands[0]?.id||""),[year,setYear]=useState(String(new Date().getFullYear()+1)),[sourceType,setSourceType]=useState("ftp"),[sourceUrl,setSourceUrl]=useState("");
 const byBrand=useMemo(()=>new Map(brands.map(b=>[b.id,b])),[brands]); const s=createClient();
 async function addStore(){if(!storeName.trim())return;setBusy(true);const{error}=await s.from("stores").insert({name:storeName.trim(),slug:slugify(storeName),is_published:false});setBusy(false);if(error)alert(error.message);else location.reload()}
 async function addBrand(){if(!brandName.trim())return;setBusy(true);const{error}=await s.from("brands").insert({name:brandName.trim(),slug:slugify(brandName)});setBusy(false);if(error)alert(error.message);else location.reload()}
 async function logo(b:any,f:File){setBusy(true);const ext=f.name.split(".").pop()||"png",path=`logos/${b.slug}-${Date.now()}.${ext}`;const up=await s.storage.from("brand-assets").upload(path,f,{contentType:f.type});if(up.error){alert(up.error.message);setBusy(false);return}const url=s.storage.from("brand-assets").getPublicUrl(path).data.publicUrl;const{error}=await s.from("brands").update({logo_url:url}).eq("id",b.id);setBusy(false);if(error)alert(error.message);else location.reload()}
 async function epos(files:FileList|null){if(!files?.length||!brandId)return;setBusy(true);for(const f of Array.from(files)){const path=`epos/${brandId}/${year}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await s.storage.from("brand-assets").upload(path,f,{contentType:f.type});if(up.error){alert(up.error.message);continue}await s.from("brand_sources").insert({brand_id:brandId,source_type:"epos_file",label:`EPOS ${year}`,file_path:path,file_name:f.name,mime_type:f.type,model_year:Number(year),status:"pending"})}setBusy(false);location.reload()}
 async function addFeed(){if(!brandId||!sourceUrl.trim())return;setBusy(true);const{error}=await s.from("brand_sources").insert({brand_id:brandId,source_type:sourceType,label:`${sourceType.toUpperCase()} ${year}`,source_url:sourceUrl.trim(),model_year:Number(year),status:"configured"});setBusy(false);if(error)alert(error.message);else location.reload()}
 return <main className="superAdmin"><aside><b>bikéo <i>ADMIN</i></b>{["overview","stores","brands","data"].map(x=><button className={tab===x?"on":""} onClick={()=>setTab(x)} key={x}>{x==="overview"?"Vue d'ensemble":x==="stores"?"Magasins":x==="brands"?"Marques":"EPOS & flux"}</button>)}<a href="/dashboard">← Espace magasin</a></aside><section><header><small>SUPERADMIN BIKÉO · PROTOTYPE</small><h1>{tab==="overview"?"Pilotage de la plateforme":tab==="stores"?"Magasins partenaires":tab==="brands"?"Référentiel marques":"Données marques & EPOS"}</h1><p>Administration centrale Bikéo. Cet accès /admin est volontairement ouvert pendant le développement.</p></header>
 {tab==="overview"&&<div className="adminStats"><article><strong>{stores.length}</strong><span>magasin</span></article><article><strong>{brands.length}</strong><span>marques référencées</span></article><article><strong>{products.length}</strong><span>produits catalogue</span></article><article><strong>{sources.length}</strong><span>sources de données</span></article></div>}
 {tab==="stores"&&<><div className="adminCreate"><input placeholder="Nom du nouveau magasin" value={storeName} onChange={e=>setStoreName(e.target.value)}/><button disabled={busy} onClick={addStore}>Créer le magasin</button></div><div className="adminTable">{stores.map(x=><div key={x.id}><b>{x.name}</b><span>{x.city||"Ville à compléter"}</span><code>/magasin/{x.slug}</code><em>{x.is_published?"Publié":"Brouillon"}</em></div>)}</div></>}
 {tab==="brands"&&<><div className="adminCreate"><input placeholder="Nouvelle marque Bikéo" value={brandName} onChange={e=>setBrandName(e.target.value)}/><button disabled={busy} onClick={addBrand}>Créer la marque</button></div><div className="adminBrandGrid">{brands.map(b=><article key={b.id}><div>{b.logo_url?<img src={b.logo_url}/>:<span>{b.name}</span>}</div><b>{b.name}</b><small>{products.filter(p=>p.brand_id===b.id).length} produits</small><label>Logo officiel<input type="file" accept="image/*,.svg" onChange={e=>e.target.files?.[0]&&logo(b,e.target.files[0])}/></label></article>)}</div></>}
 {tab==="data"&&<><div className="adminDataForm"><h2>Ajouter des données marque</h2><div><select value={brandId} onChange={e=>setBrandId(e.target.value)}>{brands.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><input type="number" value={year} onChange={e=>setYear(e.target.value)}/></div><label className="eposDrop"><b>EPOS / catalogue marque</b><span>PDF, CSV ou XLSX · plusieurs fichiers possibles pour un même millésime</span><input multiple type="file" accept=".pdf,.csv,.xls,.xlsx" disabled={busy} onChange={e=>epos(e.target.files)}/></label><div className="feedRow"><select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="ftp">FTP</option><option value="sftp">SFTP</option><option value="api">API</option><option value="url">URL / CSV distant</option></select><input placeholder="URL ou adresse du flux" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/><button onClick={addFeed} disabled={busy}>Ajouter le flux</button></div></div><div className="adminTable">{sources.map(x=><div key={x.id}><b>{byBrand.get(x.brand_id)?.name||"Marque"}</b><span>{x.label||x.source_type}</span><code>{x.file_name||x.source_url||"—"}</code><em>{x.status}</em></div>)}</div></>}
 </section></main>}