"use client";import {useMemo,useState} from "react";import {createClient} from "../lib/supabase/client";
const slugify=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export default function SuperAdmin({stores,brands,sources,products}:{stores:any[];brands:any[];sources:any[];products:any[]}){const[tab,setTab]=useState("overview"),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[brandName,setBrandName]=useState(""),[storeName,setStoreName]=useState(""),[brandId,setBrandId]=useState(brands.find(b=>b.name==="Orbea")?.id||brands[0]?.id||""),[year,setYear]=useState("2027"),[sourceType,setSourceType]=useState("ftp"),[sourceUrl,setSourceUrl]=useState("");const byBrand=useMemo(()=>new Map(brands.map(b=>[b.id,b])),[brands]);const s=createClient();
async function addStore(){if(!storeName.trim())return;setBusy(true);const{error}=await s.from("stores").insert({name:storeName.trim(),slug:slugify(storeName),is_published:false});setBusy(false);if(error)alert(error.message);else location.reload()}
async function addBrand(){if(!brandName.trim())return;setBusy(true);const{error}=await s.from("brands").insert({name:brandName.trim(),slug:slugify(brandName)});setBusy(false);if(error)alert(error.message);else location.reload()}
async function logo(b:any,f:File){setBusy(true);const ext=f.name.split(".").pop()||"png",path=`logos/${b.slug}-${Date.now()}.${ext}`;const up=await s.storage.from("brand-assets").upload(path,f,{contentType:f.type});if(up.error){alert(up.error.message);setBusy(false);return}const url=s.storage.from("brand-assets").getPublicUrl(path).data.publicUrl;const{error}=await s.from("brands").update({logo_url:url}).eq("id",b.id);setBusy(false);if(error)alert(error.message);else location.reload()}
async function epos(files:FileList|null){if(!files?.length||!brandId)return;setBusy(true);setMsg(`Envoi de ${files.length} fichier(s)…`);let ok=0;for(const file of Array.from(files)){const fd=new FormData();fd.append("brand_id",brandId);fd.append("model_year",year);fd.append("file",file);const res=await fetch("/api/admin/brand-source",{method:"POST",body:fd});const out=await res.json();if(!res.ok){setMsg(`Erreur sur ${file.name} : ${out.error}`);setBusy(false);return}ok++}setMsg(`✓ ${ok} fichier(s) EPOS enregistré(s). Ils apparaissent ci-dessous en « À traiter ».`);setBusy(false);setTimeout(()=>location.reload(),900)}
async function addFeed(){if(!brandId||!sourceUrl.trim())return;setBusy(true);const{error}=await s.from("brand_sources").insert({brand_id:brandId,source_type:sourceType,label:`${sourceType.toUpperCase()} ${year}`,source_url:sourceUrl.trim(),model_year:Number(year),status:"configured"});setBusy(false);if(error)setMsg("Erreur : "+error.message);else{setMsg("✓ Flux enregistré.");setTimeout(()=>location.reload(),700)}}
return <main className="superAdmin"><aside><b>bikéo <i>ADMIN</i></b>{[["overview","Vue d'ensemble"],["stores","Magasins"],["brands","Marques"],["data","EPOS & flux"]].map(([x,l])=><button className={tab===x?"on":""} onClick={()=>setTab(x)} key={x}>{l}</button>)}<a href="/dashboard">← Espace magasin</a></aside><section><header><small>SUPERADMIN BIKÉO · PROTOTYPE</small><h1>{tab==="overview"?"Pilotage de la plateforme":tab==="stores"?"Magasins partenaires":tab==="brands"?"Référentiel marques":"Données marques & EPOS"}</h1><p>Administration centrale Bikéo. Cet accès /admin est volontairement ouvert pendant le développement.</p></header>
{tab==="overview"&&<div className="adminStats"><article><strong>{stores.length}</strong><span>magasin</span></article><article><strong>{brands.length}</strong><span>marques référencées</span></article><article><strong>{products.length}</strong><span>produits catalogue</span></article><article><strong>{sources.length}</strong><span>sources enregistrées</span></article></div>}
{tab==="stores"&&<><div className="adminCreate"><input placeholder="Nom du nouveau magasin" value={storeName} onChange={e=>setStoreName(e.target.value)}/><button disabled={busy} onClick={addStore}>Créer le magasin</button></div><div className="adminTable">{stores.map(x=><div key={x.id}><b>{x.name}</b><span>{x.city||"Ville à compléter"}</span><code>/magasin/{x.slug}</code><em>{x.is_published?"Publié":"Brouillon"}</em></div>)}</div></>}
{tab==="brands"&&<><div className="adminCreate"><input placeholder="Nouvelle marque Bikéo" value={brandName} onChange={e=>setBrandName(e.target.value)}/><button disabled={busy} onClick={addBrand}>Créer la marque</button></div><div className="adminBrandGrid">{brands.map(b=><article key={b.id}><div>{b.logo_url?<img src={b.logo_url}/>:<span>{b.name}</span>}</div><b>{b.name}</b><small>{products.filter(p=>p.brand_id===b.id).length} produits</small><label>Logo officiel<input type="file" accept="image/*,.svg" onChange={e=>e.target.files?.[0]&&logo(b,e.target.files[0])}/></label></article>)}</div></>}
{tab==="data"&&<><div className="adminDataForm"><h2>Ajouter des données marque</h2><div><select value={brandId} onChange={e=>setBrandId(e.target.value)}>{brands.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><input type="number" value={year} onChange={e=>setYear(e.target.value)}/></div><label className="eposDrop"><b>EPOS / catalogue marque</b><span>PDF, CSV ou XLSX · plusieurs fichiers possibles · 100 Mo max par fichier</span><input multiple type="file" accept=".pdf,.csv,.xls,.xlsx" disabled={busy} onChange={e=>epos(e.target.files)}/></label>{msg&&<div className={msg.startsWith("✓")?"adminMessage ok":"adminMessage"}>{msg}</div>}<div className="feedRow"><select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="ftp">FTP</option><option value="sftp">SFTP</option><option value="api">API</option><option value="url">URL / CSV distant</option></select><input placeholder="URL ou adresse du flux" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/><button onClick={addFeed} disabled={busy}>Ajouter le flux</button></div></div><h2>Sources enregistrées</h2><div className="adminTable">{sources.length?sources.map(x=><div key={x.id}><b>{byBrand.get(x.brand_id)?.name||"Marque"}</b><span>{x.label||x.source_type}</span><code>{x.file_name||x.source_url||"—"}</code><em className={"sourceStatus "+x.status}>{x.status==="pending"?"À traiter":x.status==="imported"?`Importé · ${x.imported_products||0} produits`:x.status==="error"?"Erreur":x.status==="configured"?"Configuré":x.status}</em></div>):<p className="emptyAdmin">Aucun EPOS ou flux enregistré.</p>}</div></>}
</section></main>}