export type BikeSemanticProfile={primaryType:string;intents:string[];motor?:string;electric:boolean;lightweightElectric:boolean;keywords:string[]};
const norm=(v:unknown)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export function getBikeSemanticProfile(product:any):BikeSemanticProfile{
 const specs=product?.specs||{};const name=norm(product?.name);const category=norm(product?.category);const family=norm(specs.family||product?.family);const motorRaw=String(specs.motor||product?.motor_system||"").trim();const motor=norm(motorRaw);const battery=norm(specs.battery);const all=[name,category,family,motor,battery].join(" ");
 const isAvinox=/avinox|dji/.test(all);const electric=Boolean(motorRaw||battery)||/electri|ebike|e-bike|vae|vttae|avinox/.test(all);const isRoad=/route|road/.test(category+" "+family)||/\bgain\b/.test(name+" "+family);const isMtb=/vtt|mtb|mountain/.test(category+" "+family)||/\bwild\b/.test(name+" "+family);const isGravel=/gravel/.test(category+" "+family);const lightweightElectric=electric&&(isRoad&&(/\bgain\b/.test(name+" "+family)||/light|leger|rs/.test(all)));
 let primaryType=product?.category||"Vélo";const intents:string[]=[];
 if(isMtb&&electric){primaryType="VTT électrique";intents.push("VTT électrique","VTTAE","e-MTB");}else if(isRoad&&electric){primaryType=lightweightElectric?"Vélo de route électrique léger":"Vélo de route électrique";intents.push("vélo de route électrique","e-road");}else if(isGravel&&electric){primaryType="Gravel électrique";intents.push("gravel électrique","e-gravel");}else if(isRoad){primaryType="Vélo de route";intents.push("vélo de route");}else if(isMtb){primaryType="VTT";intents.push("VTT");}else if(isGravel){primaryType="Gravel";intents.push("gravel");}
 if(lightweightElectric)intents.push("vélo de route électrique léger","vélo électrique léger","route électrique léger");if(isAvinox){intents.push("vélo moteur Avinox","vélo DJI Avinox");if(isMtb)intents.push("VTT Avinox","VTT électrique Avinox","VTTAE Avinox");}
 const keywords=Array.from(new Set([primaryType,...intents,product?.brands?.name,product?.name,motorRaw].filter(Boolean).map(String)));return{primaryType,intents:Array.from(new Set(intents)),motor:motorRaw||undefined,electric,lightweightElectric,keywords};}
export function buildBikeDescription(product:any,store:any,semantic=getBikeSemanticProfile(product)){const brand=product?.brands?.name||"";const model=product?.name||"vélo";const city=store?.city?" à "+store.city:"";const motor=semantic.motor?" Motorisation : "+semantic.motor+".":"";return (brand+" "+model+", "+semantic.primaryType.toLowerCase()+", proposé par "+(store?.name||"ce magasin")+city+"."+motor).replace(/\s+/g," ").trim();}