import { createClient } from "./supabase/server";
import { cache } from "react";
const getStoreCached=cache(async (slug:string)=>{const supabase=await createClient();const {data,error}=await supabase.from("stores").select("*").eq("slug",slug).single();if(error)throw error;return data});
export async function getStore(slug="cycles-omega"){return getStoreCached(slug)}
export async function getDemoStore(){return getStoreCached("cycles-omega")}
export async function getCurrentStore(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Non autorisé");const{data:membership,error:membershipError}=await supabase.from("store_members").select("store_id").eq("user_id",user.id).limit(1).maybeSingle();if(membershipError)throw membershipError;if(!membership?.store_id)throw new Error("Aucun magasin associé");const{data:store,error:storeError}=await supabase.from("stores").select("*").eq("id",membership.store_id).maybeSingle();if(storeError)throw storeError;if(!store)throw new Error("Magasin introuvable");return store}
export async function getCatalog(storeSlug="cycles-omega"){const supabase=await createClient();const store=await getStoreCached(storeSlug);const {data:links,error:linkError}=await supabase.from("store_brands").select("brand_id").eq("store_id",store.id);if(linkError)throw linkError;const brandIds=(links??[]).map(x=>x.brand_id);if(!brandIds.length)return[];const {data,error}=await supabase.from("products").select("*, brands(name), product_variants(id,size,color,ean,sku,image_url)").in("brand_id",brandIds).eq("is_active",true).order("name");if(error)throw error;const variantIds=(data??[]).flatMap((p:any)=>(p.product_variants??[]).map((v:any)=>v.id));let inventory:any[]=[];if(variantIds.length){/* Fetch bounded PostgREST chunks concurrently instead of serially. */const chunks:string[][]=[];for(let i=0;i<variantIds.length;i+=200)chunks.push(variantIds.slice(i,i+200));const results=await Promise.all(chunks.map(ids=>supabase.from("inventory").select("product_variant_id,quantity,price_cents,public_status,last_synced_at,source").eq("store_id",store.id).in("product_variant_id",ids)));for(const r of results){if(r.error)throw new Error(r.error.message||"Erreur lecture stock");inventory.push(...(r.data??[]))}}const byVariant=new Map<string,any[]>();inventory.forEach(i=>byVariant.set(i.product_variant_id,[...(byVariant.get(i.product_variant_id)||[]),i]));return (data??[]).map((p:any)=>({...p,product_variants:(p.product_variants??[]).map((v:any)=>({...v,inventory:byVariant.get(v.id)||[]}))}))}
export async function getProductForStore(storeSlug:string,productSlug:string){const products:any[]=await getCatalog(storeSlug);return products.find(p=>p.slug===productSlug)??null}
export async function getStoreStats(storeSlug="cycles-omega"){const products:any[]=await getCatalog(storeSlug);const variants=products.flatMap(p=>p.product_variants??[]);const inventory=variants.flatMap(v=>v.inventory??[]);return{products:products.length,inStock:inventory.filter(i=>i.public_status==="in_stock"&&i.quantity>0).reduce((n:number,i:any)=>n+i.quantity,0),orderable:inventory.filter(i=>i.public_status==="orderable").length,lastSync:inventory.map(i=>i.last_synced_at).filter(Boolean).sort().at(-1)??null}}

export async function getStoreBrands(storeSlug="cycles-omega"){const supabase=await createClient();const store=await getStore(storeSlug);const {data,error}=await supabase.from("store_brands").select("is_featured,logo_override_url,brands(id,name,slug,logo_url,website_url)").eq("store_id",store.id);if(error)throw error;return (data??[]).map((x:any)=>({...x.brands,logo_url:x.logo_override_url||x.brands?.logo_url,is_featured:x.is_featured})).filter(Boolean)}


export async function getStoreLoyaltyIntegration(storeId:string){const supabase=await createClient();const {data}=await supabase.from("store_loyalty_integrations").select("external_business_id,external_slug,status").eq("store_id",storeId).maybeSingle();return data??null}


export async function getStoreLoyaltyPublicData(externalBusinessId:string|null|undefined){if(!externalBusinessId)return null;const base=process.env.DIGIFYD_API_URL,secret=process.env.DIGIFYD_BIKEO_SECRET;if(!base||!secret)return null;try{const r=await fetch(base.replace(/\/$/,"")+"/api/integrations/bikeo/business-data?businessId="+encodeURIComponent(externalBusinessId),{headers:{"x-bikeo-secret":secret},cache:"no-store"});if(!r.ok)return null;const x=await r.json();return x?.data??x??null}catch{return null}}


export async function getPublishedStoresForSeo(){const supabase=await createClient();const{data,error}=await supabase.from("stores").select("id,name,slug,city,postal_code,address_line1,phone,email,logo_url,website_url,updated_at").eq("is_published",true).order("slug");if(error)throw error;return data??[]}
export async function getSeoCatalog(){const supabase=await createClient();const{data:stores,error:se}=await supabase.from("stores").select("id,name,slug,city,postal_code,updated_at").eq("is_published",true);if(se)throw se;const{data:links,error:le}=await supabase.from("store_brands").select("store_id,brand_id");if(le)throw le;const brandIds=Array.from(new Set((links??[]).map((x:any)=>x.brand_id)));if(!brandIds.length)return{stores:stores??[],links:links??[],products:[]};const{data:products,error:pe}=await supabase.from("products").select("id,brand_id,name,slug,category,model_year,motor_system,specs,image_url,updated_at,brands(name)").in("brand_id",brandIds).eq("is_active",true);if(pe)throw pe;return{stores:stores??[],links:links??[],products:products??[]}}
